### ISSUE TITLE
evaluation_score is NaN

### ISSUE THREAD

**Issue by AsaiSyuu** [fg91/Deep-Q-Learning#1]
I have been running this code for several days, it works quite well. But sometimes its evaluation_score returns NaN, I couldn't figure out why... Has anybody run into this? Thanks!
![Uploading Screen Shot 2018-08-22 at 20.23.33.png…]()

**Comment by fg91** [comment]
Hey,
unfortunately I can't open the picture. However, I think I can tell you what is happening because I have seen the same in Breakout.
I trained the DQN on a deterministic version of the Breakout environment which means that there is no randomness involved. I observed two times "that the agent got stuck in a loop".
What I mean by that is that the the paddle hit the ball, it bounced back from the wall, the paddle hit it again and shot it at the exact same spot at the wall where it got reflected in the exact same way. I saw this happening when most blocks were already cleared. Since in deterministic environments there is no randomness involved, the agent can't recover from this loop, it will do the exact same thing for the remaining frames of the evaluation (10.000 frames totally). If not a single evaluation episode was finished, no episode reward will be appended to the list `eval_rewards` and `np.mean(eval_rewards)` in this line `summ = sess.run(EVAL_SCORE_SUMMARY, feed_dict={EVAL_SCORE_PH:np.mean(eval_rewards)})` will give NaN.
The code crashed on me after more than two days of training, because I tried passing `eval_rewards[0]` to the `generate_gif` function, which gives an index error when not a single evaluation episode terminated. That's why the `try` is needed.
try:
                generate_gif(frame_number, frames_for_gif, eval_rewards[0], PATH)
            except IndexError:
                print("No evaluation game finished")

But thank you for bringing this to my attention, while fixing the issue with the `generate_gif` function, which caused the code to crash, I forgot to make sure that Nan is not passed to the summaries for tensorboard..
Did you see "No evaluation game finished" in the output when seeing NaN (I assume in tensorboard)? 
And may I ask which environment you trained the DQN on? :)

Best regards
Fabio

**Comment by AsaiSyuu** [comment]
@fg91 Thank you for your reply!
<img width="890" alt="screen shot 2018-09-07 at 21 34 10" src="https://user-images.githubusercontent.com/27881443/45222131-2226f200-b2e6-11e8-96e6-bfd6553edf68.png">
this is the picture i posted.

I trained the Breakout, and i think the problem is exactly what you say. I just paid attention to tensorboard and forgot to check the output. After checking the output, there is "No evaluation game finished" after nan appears. The better the agent performs, the more likely it got stuck in such a loop. 

Best Wishes
Syuu

**Comment by fg91** [comment]
Yes, in Breakout this can only happen if there is already a hole in the wall of bricks so that the ball can bounce back from the ceiling, get hit by the paddle and then hit the exact same spot at the ceiling again. Therefore it appears only when the agent already performs quite well. I also saw a loop "paddle, side wall, ceiling, paddle, side wall, ceiling,...".

Best regards
Fabio
